# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Latest Android orbs
orbs:
  android: circleci/android@1.0.3

jobs:
  # Name of the job
  build-and-test:
    # Android Executor
    # See: https://circleci.com/docs/2.0/executor-types/
    executor:
      name: android/android-machine

    steps:
      # Checkout the code as the first step.
      - checkout
      
      # Restore the build cache
      - restore_cache:
          key: android-orb-v1-
          name: Restore build cache
      
      # Run to get gradle permission
      - run:
          name: Get Gradle Permission
          command: chmod +x ./gradlew

      # Save the Android build-cache
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          name: Save build cache
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

      # Gradle Build
      - run:
          name: Run Build
          command: ./gradlew build

      # The next step will run the unit tests
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue
          
      - store_test_results:
          path: test-results

      # Save Build report/insight
      - store_artifacts:
          path: app/build/reports
          destination: reports

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  submission-2: 
    # run jobs
    jobs:
      - build-and-test
